import '../css/app.css';
import './bootstrap';

import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';
import { createApp, h } from 'vue';

// ✅ Import ZiggyVue from NPM, not vendor/
import { ZiggyVue } from 'ziggy-js';
import { Ziggy } from './ziggy'; // generated by `php artisan ziggy:generate resources/js/ziggy.js`

const appName = import.meta.env.VITE_APP_NAME || 'Laravel';

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) =>
        resolvePageComponent(
            `./Pages/${name}.vue`,
            import.meta.glob('./Pages/**/*.vue')
        ),

    setup({ el, App, props, plugin }) {
        const app = createApp({ render: () => h(App, props) });

        app.use(plugin);
        app.use(ZiggyVue, Ziggy); // ✅ pass Ziggy

        // Simple translator helper
        app.config.globalProperties.__ = (key) => {
            const translations = props.initialPage?.props?.translations;
            return translations && translations[key] ? translations[key] : key;
        };

        app.mount(el);
    },

    progress: {
        color: '#4B5563',
    },
});
